### ISSUE TITLE
Cannot do `seth call` without any calldata

### ISSUE THREAD

**Issue by reverendus** [dapphub/seth#12]
Although it's not possible in Solidity to have a fallback function return a value, is might not necessarily be the case for a general contract wrote directly in EVM.

Do we want to make `seth call` support it...?

**Comment by dbrock** [comment]
You can always do `seth call @foo 0x`. I'm not sure if it's more useful for `seth call @foo` to make an empty call or show usage help...

**Comment by reverendus** [comment]
Fair enough. I would prefer the latter. Closing.
