### ISSUE TITLE
register public key fails

### ISSUE THREAD

**Issue by ranveerkunal** [dapphub/seth#15]
seth send -F "ETH-ADDRESS" -G 4600000 "CONTRACT-ADDRESS" "register(bytes)" "EOS....gstdr"
ethabi: error: Tokenizer(FromHex(Invalid character 'O' at position 1))

**Comment by ranveerkunal** [comment]
I think it is trying to interpret public key as hex. thus giving error for O at position 1.

**Comment by ranveerkunal** [comment]
seth send -F "ETH-ADDRESS" -G 4600000 "CONTRACT-ADDRESS" "register(string)" "EOS....gstdr"
changing argument to string works. May be fix documentation. If it is actually bytes, then we need to convert the above string into bytes.
Please advise, what is the right way to do it.

**Comment by dbrock** [comment]
To encode ASCII text into `bytes`, you would do the following:

    seth send $contract "foo(bytes)" $(seth --from-ascii yourtext)

However, in the case of the EOS sale contract, it should actually be `register(string)`, so this is in fact correct:

    seth send $eos_sale "register(string)" "EOS....gstdr"
