### ISSUE TITLE
automate/bundle deps

### ISSUE THREAD

**Issue by kumavis** [dapphub/seth#2]
bc manually installing deps is annoying

**Comment by dbrock** [comment]
You're absolutely right, lol.

We currently recommend using Nix (<https://nixos.org/nix>) to install dependencies:

```
curl https://nixos.org/nix/install | sh
nix-env -i ethabi jshon
git clone https://github.com/dapphub/seth
make link -C seth
```

I'll add this to the README.

We're working on adding our whole toolchain to the official Nix package repository. Once that's done, you'd be able to install Seth and all its dependencies by simply doing `nix-env -i seth`.
