### ISSUE TITLE
JSON Parse error

### ISSUE THREAD

**Issue by kennyrowe** [dapphub/seth#26]
While trying to check balances of a few accounts I found some odd behavior.

```
$ seth balance 0x01C4f84a43BC3162a6aa911B54044A9f2345325E
0.096005288000000000E+18

$ seth balance 0x1aac276635c4bDDa35Ba666e2849C0696abffD71
{"jsonrpc":"2.0","id":1,"result":"0x374412580c1de"}

```

`Seth` seems to have an issue parsing the json response from the second account. After digging a little deeper I found this.

```
$ echo $smallBalance
{"jsonrpc":"2.0","id":1,"result":"0x374412580c1de"}

$ echo $balance
{"jsonrpc":"2.0","id":1,"result":"0x155144cffcc9000"}

$ seth --show-json <<<$(rpc-result <<<$balance)
96005288000000000

$ seth --show-json <<<$(rpc-result <<<$smallBalance)

```

It looks like `--show-json` isn't parsing correctly.

**Comment by dbrock** [comment]
Okay, we need to consider `jshon` to be deprecated. There should be a warning about this.

Thanks @kennyrowe, that's a crazy bug you discovered. It does not happen with @mbrock's `jshon` replacement dapphub/jays, which should be what is used by default.

How did you install `seth` and `jshon`?

**Comment by kennyrowe** [comment]
@dbrock `seth` from source since nix didn't seem to have some of the new features (though they have the same version number)

I can't remember how I installed `jshon` but I do remember it wasn't easy
