### ISSUE TITLE
Flags may not work

### ISSUE THREAD

**Issue by hanchang** [dapphub/seth#32]
**Expected Behavior:**
Flags should set config settings.

**Actual Behavior:**
Flags may not be detected as config settings, whereas environment variables are.

**Example:**

Passing in config settings via flags throws a `ethsign: account not found` error:
```
$ seth --from=0xd089f28d0a151439298b9858030957edb1cb87cb --keystore=~/Code/Ethereum/localtestnet/keystore/ send $COFI_AIRDROP "sendAirdrop(address[])" $ADDRESSES
seth-send: warning: `ETH_GAS' not set; using default gas amount
ethsign: account not found
```

Using environment variables solves the issue:
```
$ export ETH_FROM=0xd089f28d0a151439298b9858030957edb1cb87cb
$ export ETH_KEYSTORE=~/Code/Ethereum/localtestnet/keystore/
$ seth send $COFI_AIRDROP "sendAirdrop(address[])" $ADDRESSES
seth-send: warning: `ETH_GAS' not set; using default gas amount
Ethereum account passphrase (not echoed): seth-send: Published transaction with 132 bytes of calldata.
seth-send: 0xfcee0e71cb383c8f41a2aaaa9a88f637a8728d1277784f255afd404c71728e15
seth-send: Waiting for transaction receipt...
seth-send: Transaction included in block 28.
```

**Comment by nanexcool** [comment]
This error was caused by `--keystore=~/Code/Ethereum/localtestnet/keystore/` where bash is not expanding `~`

In this case you can remove `=` and use `--keystore ~/Code/Ethereum/localtestnet/keystore/`
